### PR TITLE
Pin Pydantic to version 1

### LINKED ISSUE #85: Pin pydantic to version 1 until updating to pydantic 2

### PR DESCRIPTION
**Pull request by DiamondJoseph**
- Prevent deprecation exceptions from np.product
- Prevent deprecation exceptions from fastapi example
- Update schema.json
- Closes #85

### CODE REVIEW

**Comment by DiamondJoseph** [comment]
Looks like only docs CI ran: does opening a PR not cause the code_ci to run?

**Comment by coretl** [comment]
code ci has a scheduled job, which was disabled due to lack of activity, I've re-enabled it, and will power cycle this PR to make it run again...

**Comment by coretl** [comment]
Annoying, can you push another commit please?

**Comment by DiamondJoseph** [comment]
(approved by Tom verbally)

**Pull request merged**
