### PR TITLE
Fix/matplotlib 3.5.0

### LINKED ISSUE #42: Issue with drawing arrows in matplotlib 3.5.0
Currently when trying to use the CLI you get an error when it tries to draw the arrows:

```
[cvl62853@pc0110 scanspec]$ pipenv run scanspec plot 'Snake(Line("z", 5, 6, 2) * Line("y", 2, 3, 2) * Line("x", 1, 2, 2))'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/dls_sw/prod/tools/RHEL7-x86_64/Python3/3-7-2dls1/prefix/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/dls_sw/prod/tools/RHEL7-x86_64/Python3/3-7-2dls1/prefix/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 251, in idle_draw
    self.draw()
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 9, in draw
    super().draw()
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/figure.py", line 2804, in draw
    renderer, self, artists, self.suppressComposite)
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 449, in draw
    reverse=True):
  File "/scratch/cvl62853/pipenv/scanspec-ajHh2QfZ/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 436, in do_3d_projection
    return artist.do_3d_projection(renderer)
AttributeError: '_Arrow3D' object has no attribute 'do_3d_projection'
```
Issue is here: https://github.com/matplotlib/matplotlib/issues/21688

Fix was to re-add a (deprecated) method to their Arrow3D class:
```
    def do_3d_projection(self, renderer=None):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, self.axes.M)
        self.set_positions((xs[0], ys[0]), (xs[1], ys[1]))

        return np.min(zs)
```
This fixes the plotting, but you still get test failures for 3d plots:
```
Traceback (most recent call last):
  File "/dls/science/users/cvl62853/support/python/scanspec/tests/test_cli.py", line 212, in test_plot_3D_line
    assert len(artists) == 4
AssertionError: assert 0 == 4
  +0
  -4
```

### PR DESCRIPTION
**Pull request by BenBradnick**
This fixes #42.

- Pipfile.lock is updated to matplotlib 3.5.0
- _Arrow3D has re-added method do_3d_projection()
- 3D plot unit test has updated check for arrow artists

### CODE REVIEW

**Comment by thomascobb** [comment]
Can you update https://github.com/dls-controls/scanspec/blob/master/src/scanspec/sphinxext.py#L17 to take *args **kwargs please?

**Comment by thomascobb** [comment]
Do the docs with 3D arrows look right locally?

**Comment by BenBradnick** [comment]
> Do the docs with 3D arrows look right locally?

I believe so from checking the test spec - not sure if there's any more rigorous testing that should be done?

image

**Comment by BenBradnick** [comment]
Should I write any unit tests for the Arrow3D class to make codecov happy?

**Comment by thomascobb** [comment]
> Should I write any unit tests for the Arrow3D class to make codecov happy?

They used to be covered by the plotting test that you had to change, I wonder why that isn't the case anymore?

**Comment by BenBradnick** [comment]
> > Should I write any unit tests for the Arrow3D class to make codecov happy?
> 
> They used to be covered by the plotting test that you had to change, I wonder why that isn't the case anymore?

It looks like it is only complaining about the few new lines in the do_3d_projection method that was added.

I also imported annotations from __future__, I believe the type hints are now all updated.

**Comment by tacaswell** [comment]
You should also remove the duplicate logic from `draw`.  It not really harmful as-is,but you are doing some extra computation.

**Comment by thomascobb** [comment]
Thanks, done in #45

**Pull request merged**
